"use client";

import { XIcon } from "lucide-react";
import React from "react";
import { Button } from "@/registry/react/components/button";
import {
  FileUpload,
  FileUploadDropzone,
  FileUploadDropzoneIcon,
  FileUploadItem,
  FileUploadItemDeleteTrigger,
  FileUploadItemGroup,
  FileUploadItemPreview,
  FileUploadItemPreviewImage,
  FileUploadTitle,
  useFileUploadContext,
} from "@/registry/react/components/file-upload";

const Example = () => {
  const [acceptedFiles, setAcceptedFiles] = React.useState<File[]>([
    new File([img], "image-cropper.svg", {
      type: "image/svg+xml",
    }),
  ]);

  return (
    <FileUpload
      accept="image/*"
      acceptedFiles={acceptedFiles}
      className="w-full max-w-xs"
      maxFiles={3}
      onFileChange={(details) => setAcceptedFiles(details.acceptedFiles)}
    >
      <FileUploadDropzone className="min-h-36">
        <FileUploadDropzoneIcon />
        <FileUploadTitle>Drop images here</FileUploadTitle>
      </FileUploadDropzone>
      <CustomPreviewList />
    </FileUpload>
  );
};

const CustomPreviewList = () => {
  const { acceptedFiles } = useFileUploadContext();

  if (acceptedFiles.length === 0) {
    return null;
  }

  return (
    <FileUploadItemGroup className="grid grid-cols-2 gap-3 sm:grid-cols-3">
      {acceptedFiles.map((file) => (
        <FileUploadItem
          className="group/item aspect-square overflow-hidden rounded-xl border bg-muted shadow-xs/4"
          file={file}
          key={file.name}
        >
          <FileUploadItemPreview className="size-full" type="image/*">
            <FileUploadItemPreviewImage className="rounded-none" />
          </FileUploadItemPreview>
          <FileUploadItemDeleteTrigger asChild>
            <Button
              aria-label={`Remove ${file.name}`}
              className="absolute inset-e-2 top-2 opacity-100 shadow-sm/4 transition-opacity duration-150 ease-out motion-reduce:transition-none sm:opacity-0 sm:group-hover/item:opacity-100 sm:group-focus-within/item:opacity-100"
              pill
              size="icon-xs"
              variant="secondary"
            >
              <XIcon />
            </Button>
          </FileUploadItemDeleteTrigger>
        </FileUploadItem>
      ))}
    </FileUploadItemGroup>
  );
};

const img = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" fill="none" shape-rendering="auto" aria-hidden="true"><!-- Generated by DiceBear (https://www.dicebear.com) --><metadata xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dcterms="http://purl.org/dc/terms/"><rdf:RDF><rdf:Description><dc:title>Waves</dc:title><dc:creator>DiceBear</dc:creator><dc:source xsi:type="dcterms:URI">https://www.dicebear.com</dc:source><dcterms:license xsi:type="dcterms:URI">https://creativecommons.org/publicdomain/zero/1.0/</dcterms:license><dc:rights>“Waves” (https://www.dicebear.com) by “DiceBear”, licensed under “CC0 1.0” (https://creativecommons.org/publicdomain/zero/1.0/)</dc:rights></rdf:Description></rdf:RDF></metadata><defs><g id="layer-calm-647ee9af"><path d="M0 16c28 0 52-6 84-5s72 10 116 5v114H0Z" fill="#1a6b5c"/></g><g id="layer-rolling-647ee9af"><path d="M0 8c12 0 23 16 35 16S58 8 70 8s23 16 35 16 23-16 35-16 23 16 35 16 23-16 35-16 23 16 35 16c8 0 17-8 25-10v116H0Z" fill="#1a6b5c"/></g><g id="layer-ripple-647ee9af"><path d="M0 12c6 0 12 10 18 10s12-10 18-10 12 10 18 10 12-10 18-10 12 10 18 10 12-10 18-10 12 10 18 10 12-10 18-10 12 10 18 10 12-10 18-10 12 10 18 10 12-10 18-10 12 6 20 5v113H0Z" fill="#1a6b5c"/></g><g id="body-quintet-647ee9af"><g opacity=".14"><g class="dbwa-l1"><use transform="translate(-50) translate(-17.5128, 2.48118)" href="#layer-calm-647ee9af"/></g></g><g opacity=".24"><g class="dbwa-l2"><use transform="translate(-50 17) translate(19.3744, 1.5145)" href="#layer-rolling-647ee9af"/></g></g><g opacity=".34"><g class="dbwa-l3"><use transform="translate(-50 34) translate(-16.1806, -0.16705)" href="#layer-rolling-647ee9af"/></g></g><g opacity=".42"><g class="dbwa-l4"><use transform="translate(-50 51) translate(-14.0758, -1.51749)" href="#layer-ripple-647ee9af"/></g></g><g opacity=".48"><g class="dbwa-l5"><use transform="translate(-50 68) translate(15.8884, -0.16471)" href="#layer-rolling-647ee9af"/></g></g></g><g id="bodyFree-default-647ee9af"><use href="#body-quintet-647ee9af"/></g><g id="rotation-free-647ee9af"><use transform="rotate(-28.0663, 50, 50)" href="#bodyFree-default-647ee9af"/></g><g id="animation-none-647ee9af"></g><clipPath id="clip-647ee9af"><rect width="100" height="100" rx="0" ry="0"/></clipPath></defs><g clip-path="url(#clip-647ee9af)"><rect width="100" height="100" fill="#eef4e6"/><g transform="translate(50, 50) scale(1.2) translate(-50, -50)"><use href="#rotation-free-647ee9af"/><use href="#animation-none-647ee9af"/></g></g></svg>`;

export default Example;
