allowBuilds:
  esbuild: true
  sharp: true
minimumReleaseAgeExclude:
  - '@tanstack/form-core@1.33.0'
  - '@tanstack/react-form@1.33.0'
  - fumadocs-core@16.9.2
  - fumadocs-ui@16.9.2
  - lucide-react@1.17.0
