allowBuilds:
  esbuild: true
  node-pty: true
  sharp: true
minimumReleaseAgeExclude:
  - '@ai-sdk/gateway@4.0.76'
  - '@ai-sdk/mcp@2.0.46'
  - '@ai-sdk/provider-utils@5.0.37'
  - '@ai-sdk/provider@4.0.11'
  - '@ai-sdk/react@4.0.98'
  - ai@7.0.95
  - ultracite@7.11.1
  - valibot@1.5.0
  - '@ark-ui/react@5.39.1'
patchedDependencies:
  '@ark-ui/react@5.39.1': patches/@ark-ui__react@5.39.1.patch
