import type { RegistryItemType } from "@/lib/registry";
import { absoluteUrl } from "@/lib/url";

const dependencies = [
  "@ark-ui/react",
  "date-fns",
  "lucide-react",
  "recharts",
  "tailwind-variants",
];

const devDependencies = ["tw-animate-css"];

const SHARK_UI_BUNDLE = [
  "accordion",
  "action-bar",
  "alert",
  "alert-dialog",
  "announcement",
  "aspect-ratio",
  "autocomplete",
  "avatar",
  "badge",
  "bottom-navigation",
  "breadcrumb",
  "button",
  "button-group",
  "calendar",
  "card",
  "carousel",
  "chart",
  "checkbox",
  "circular-progress",
  "circular-slider",
  "client-only",
  "clipboard",
  "collapsible",
  "color-picker",
  "combobox",
  "command",
  "context-menu",
  "data-list",
  "date-picker",
  "dialog",
  "download-trigger",
  "drawer",
  "editable",
  "field",
  "file-upload",
  "float",
  "floating-panel",
  "format",
  "frame",
  "highlight",
  "hitbox",
  "hint",
  "hover-card",
  "image-cropper",
  "input",
  "input-group",
  "input-otp",
  "item",
  "json-tree-view",
  "kbd",
  "link-overlay",
  "listbox",
  "locale",
  "marquee",
  "menu",
  "native-select",
  "number-input",
  "pagination",
  "password-input",
  "popover",
  "presence",
  "progress",
  "prose",
  "qr-code",
  "radio-group",
  "rating",
  "resizable",
  "scroll-area",
  "segment-group",
  "select",
  "separator",
  "sheet",
  "show",
  "sidebar",
  "signature-pad",
  "skeleton",
  "skip-nav",
  "slider",
  "spinner",
  "status",
  "steps",
  "swap",
  "switch",
  "table",
  "tabs",
  "textarea",
  "timer",
  "toast",
  "toggle",
  "toggle-group",
  "toggle-tooltip",
  "tooltip",
  "tour",
  "tree-view",
] as const;

const manifest: RegistryItemType = {
  name: "ui",
  type: "registry:ui",
  dependencies,
  devDependencies,
  registryDependencies: SHARK_UI_BUNDLE.map((name) =>
    absoluteUrl(`/r/${name}.json`)
  ),
};

export default manifest;
