import type { BlockDefinition } from "@/lib/registry";
import { registryUrl } from "@/lib/url";

export const aiBlocks = [
  {
    category: "ai",
    dependencies: ["@ai-sdk/react", "ai", "lucide-react"],
    description:
      "Functional chat panel with a local createChat helper, empty state, thread, and composer.",
    files: [
      {
        path: "blocks/ai/ai-chat-01/page.tsx",
        source: "page.tsx",
        target: "app/ai-chat/page.tsx",
        type: "registry:page",
      },
      {
        path: "blocks/ai/ai-chat-01/demo.ts",
        source: "demo.ts",
        target: "@components/ai-chat/demo.ts",
        type: "registry:file",
      },
      {
        path: "blocks/ai/ai-chat-01/components/ai-chat.tsx",
        source: "components/ai-chat.tsx",
        target: "@components/ai-chat/ai-chat.tsx",
        type: "registry:component",
      },
    ],
    meta: {
      featured: true,
      order: 1,
      previewHeight: 820,
    },
    name: "ai-chat-01",
    preview: () => import("./ai-chat-01/page"),
    registryDependencies: [
      registryUrl("/r/approval-card.json"),
      registryUrl("/r/attachment.json"),
      registryUrl("/r/avatar.json"),
      registryUrl("/r/button.json"),
      registryUrl("/r/code-block.json"),
      registryUrl("/r/combobox.json"),
      registryUrl("/r/context.json"),
      registryUrl("/r/diff.json"),
      registryUrl("/r/file-upload.json"),
      registryUrl("/r/icon-tile.json"),
      registryUrl("/r/item.json"),
      registryUrl("/r/marker.json"),
      registryUrl("/r/menu.json"),
      registryUrl("/r/message.json"),
      registryUrl("/r/message-bubble.json"),
      registryUrl("/r/message-scroller.json"),
      registryUrl("/r/plan.json"),
      registryUrl("/r/popover.json"),
      registryUrl("/r/prompt-input.json"),
      registryUrl("/r/queue.json"),
      registryUrl("/r/reasoning.json"),
      registryUrl("/r/select.json"),
      registryUrl("/r/sidebar.json"),
      registryUrl("/r/sources.json"),
      registryUrl("/r/speech-input.json"),
      registryUrl("/r/toggle.json"),
      registryUrl("/r/suggestion.json"),
      registryUrl("/r/terminal.json"),
      registryUrl("/r/tool-result.json"),
      registryUrl("/r/create-chat.json"),
    ],
    title: "AI Chat",
    type: "registry:block",
  },
  {
    category: "ai",
    dependencies: ["lucide-react"],
    description:
      "Align UI–style chat sidebar with search, pinned projects, grouped history, and user footer.",
    files: [
      {
        path: "blocks/ai/ai-chat-sidebar-01/page.tsx",
        source: "page.tsx",
        target: "app/ai-chat-sidebar/page.tsx",
        type: "registry:page",
      },
      {
        path: "blocks/ai/ai-chat-sidebar-01/components/chat-sidebar.tsx",
        source: "components/chat-sidebar.tsx",
        target: "@components/ai-chat-sidebar/chat-sidebar.tsx",
        type: "registry:component",
      },
    ],
    meta: {
      featured: true,
      order: 2,
      previewHeight: 820,
    },
    name: "ai-chat-sidebar-01",
    preview: () => import("./ai-chat-sidebar-01/page"),
    registryDependencies: [
      registryUrl("/r/avatar.json"),
      registryUrl("/r/badge.json"),
      registryUrl("/r/button.json"),
      registryUrl("/r/icon-tile.json"),
      registryUrl("/r/input-group.json"),
      registryUrl("/r/separator.json"),
      registryUrl("/r/sidebar.json"),
    ],
    title: "AI Chat Sidebar",
    type: "registry:block",
  },
  {
    category: "ai",
    dependencies: ["lucide-react"],
    description:
      "Premium upgrade banner, prompt composer, model picker, think mode, and voice input.",
    files: [
      {
        path: "blocks/ai/ai-chat-composer-01/page.tsx",
        source: "page.tsx",
        target: "app/ai-chat-composer/page.tsx",
        type: "registry:page",
      },
      {
        path: "blocks/ai/ai-chat-composer-01/components/chat-composer.tsx",
        source: "components/chat-composer.tsx",
        target: "@components/ai-chat-composer/chat-composer.tsx",
        type: "registry:component",
      },
    ],
    meta: {
      featured: true,
      order: 3,
      previewHeight: 320,
    },
    name: "ai-chat-composer-01",
    preview: () => import("./ai-chat-composer-01/page"),
    registryDependencies: [
      registryUrl("/r/announcement.json"),
      registryUrl("/r/button.json"),
      registryUrl("/r/combobox.json"),
      registryUrl("/r/file-upload.json"),
      registryUrl("/r/input-group.json"),
      registryUrl("/r/popover.json"),
      registryUrl("/r/prompt-input.json"),
      registryUrl("/r/speech-input.json"),
      registryUrl("/r/toggle.json"),
    ],
    title: "AI Chat Composer",
    type: "registry:block",
  },
  {
    category: "ai",
    dependencies: ["lucide-react"],
    description:
      "Personalized empty chat state with greeting and suggestion chips.",
    files: [
      {
        path: "blocks/ai/ai-chat-empty-01/page.tsx",
        source: "page.tsx",
        target: "app/ai-chat-empty/page.tsx",
        type: "registry:page",
      },
      {
        path: "blocks/ai/ai-chat-empty-01/components/chat-empty.tsx",
        source: "components/chat-empty.tsx",
        target: "@components/ai-chat-empty/chat-empty.tsx",
        type: "registry:component",
      },
    ],
    meta: {
      featured: false,
      order: 4,
      previewHeight: 480,
    },
    name: "ai-chat-empty-01",
    preview: () => import("./ai-chat-empty-01/page"),
    registryDependencies: [registryUrl("/r/suggestion.json")],
    title: "AI Chat Empty State",
    type: "registry:block",
  },
  {
    category: "ai",
    dependencies: ["lucide-react"],
    description:
      "Rich assistant thread with reasoning, tools, approval, plan, sources, and message actions.",
    files: [
      {
        path: "blocks/ai/ai-chat-thread-01/page.tsx",
        source: "page.tsx",
        target: "app/ai-chat-thread/page.tsx",
        type: "registry:page",
      },
      {
        path: "blocks/ai/ai-chat-thread-01/demo-messages.ts",
        source: "demo-messages.ts",
        target: "@components/ai-chat-thread/demo-messages.ts",
        type: "registry:file",
      },
      {
        path: "blocks/ai/ai-chat-thread-01/components/chat-thread.tsx",
        source: "components/chat-thread.tsx",
        target: "@components/ai-chat-thread/chat-thread.tsx",
        type: "registry:component",
      },
    ],
    meta: {
      featured: true,
      order: 5,
      previewHeight: 820,
    },
    name: "ai-chat-thread-01",
    preview: () => import("./ai-chat-thread-01/page"),
    registryDependencies: [
      registryUrl("/r/approval-card.json"),
      registryUrl("/r/attachment.json"),
      registryUrl("/r/avatar.json"),
      registryUrl("/r/message-bubble.json"),
      registryUrl("/r/button.json"),
      registryUrl("/r/message.json"),
      registryUrl("/r/message-scroller.json"),
      registryUrl("/r/plan.json"),
      registryUrl("/r/reasoning.json"),
      registryUrl("/r/sources.json"),
      registryUrl("/r/suggestion.json"),
      registryUrl("/r/tool-result.json"),
      registryUrl("/r/tooltip.json"),
    ],
    title: "AI Chat Thread",
    type: "registry:block",
  },
  {
    category: "ai",
    dependencies: ["lucide-react"],
    description: "Projects grid with create CTA and workflow cards.",
    files: [
      {
        path: "blocks/ai/ai-chat-projects-01/page.tsx",
        source: "page.tsx",
        target: "app/ai-chat-projects/page.tsx",
        type: "registry:page",
      },
      {
        path: "blocks/ai/ai-chat-projects-01/components/chat-projects.tsx",
        source: "components/chat-projects.tsx",
        target: "@components/ai-chat-projects/chat-projects.tsx",
        type: "registry:component",
      },
    ],
    meta: {
      featured: false,
      order: 6,
      previewHeight: 720,
    },
    name: "ai-chat-projects-01",
    preview: () => import("./ai-chat-projects-01/page"),
    registryDependencies: [
      registryUrl("/r/button.json"),
      registryUrl("/r/card.json"),
    ],
    title: "AI Chat Projects",
    type: "registry:block",
  },
] as const satisfies readonly BlockDefinition[];
